#!/bin/sh
set -e

APUT_REPO_OWNER=$1
APUT_REPO_NAME=$2
APUT_REPO_DIST=$3
APUT_INCOMING=$4

APUT_REPO_ARCH=${5:-i386,amd64,all,source}

if [ -z $APUT_INCOMING ]; then
    echo "$0 - dput2aptly <repo_owner> <repo_name> <repo_dist> <incoming_dir> [repo_arch_list]"
    exit 2
fi

tmpdir=$APUT_INCOMING

# chown the tmpdir so that the repodir owner can access it
sudo chown -R $APUT_REPO_OWNER: $tmpdir &&
sudo su - $APUT_REPO_OWNER sh -c "aptly repo add $APUT_REPO_NAME $tmpdir" &&
# If publish does not exist, create one
sudo su - $APUT_REPO_OWNER sh -c \
    "[ -f ~/.aptly/public/dists/$APUT_REPO_DIST/Release ] || \
        aptly publish repo -architectures=$APUT_REPO_ARCH \
                           -distribution=$APUT_REPO_DIST $APUT_REPO_NAME" | \
        sed "s/your-server/$APUT_HOST/" &&
# or simply update it
sudo su - $APUT_REPO_OWNER sh -c \
    "aptly publish update $APUT_REPO_DIST" &&
# Cleanup
sudo rm -rf $tmpdir
