#!/bin/sh
set -e

APUT_REPO_OWNER=$1
APUT_REPO_NAME=$2
APUT_REPO_DIST=$3
APUT_INCOMING=$4

APUT_REPO_ARCH=${5:-i386,amd64,all,source}

if [ -z $APUT_INCOMING ]; then
    echo "$0 - dput2aptly <repo_owner> <repo_name> <repo_dist> <incoming_dir> [repo_arch_list]"
    exit 2
fi

tmpdir=$APUT_INCOMING

# Add packages in tmpdir to repo
sudo su - $APUT_REPO_OWNER sh -c "aptly repo add $APUT_REPO_NAME $tmpdir"

# Loop over possible distributions
for dist in $(echo $APUT_REPO_DIST | tr ',' ' ')
do
    # If publish does not exist, create one
    sudo su - $APUT_REPO_OWNER sh -c \
        "[ -f ~/.aptly/public/dists/$dist/Release ] || \
            aptly publish repo -architectures=$APUT_REPO_ARCH \
                               -distribution=$dist $APUT_REPO_NAME" | \
            sed "s/your-server/$APUT_HOST/" &&
    # or simply update it
    sudo su - $APUT_REPO_OWNER sh -c \
        "aptly publish update $dist"
done
# Cleanup
sudo rm -rf $tmpdir
